name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./pet-fashion-member-management/pom.xml
          mvn clean package -f ./product-management/pom.xml
          mvn clean package -f ./membership-management/pom.xml

      - name: Docker Build and push for PetFashionMemberManagement
        uses: docker/build-push-action@v4
        with:
          context: ./pet-fashion-member-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/pet-fashion-member-management:latest
            ghcr.io/${{ github.repository }}/pet-fashion-member-management:${{ github.ref_name }}
            
      - name: Docker Build and push for ProductManagement
        uses: docker/build-push-action@v4
        with:
          context: ./product-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/product-management:latest
            ghcr.io/${{ github.repository }}/product-management:${{ github.ref_name }}
            
      - name: Docker Build and push for MembershipManagement
        uses: docker/build-push-action@v4
        with:
          context: ./membership-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/membership-management:latest
            ghcr.io/${{ github.repository }}/membership-management:${{ github.ref_name }}
            
