server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: pet-fashion-member-management
          uri: http://localhost:8082
          predicates:
            - Path=/petProfiles/**, /allergySizeInfos/**, 
        - id: product-management
          uri: http://localhost:8083
          predicates:
            - Path=/products/**, 
        - id: membership-management
          uri: http://localhost:8084
          predicates:
            - Path=/members/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: pet-fashion-member-management
          uri: http://petFashionMemberManagement:8080
          predicates:
            - Path=/petProfiles/**, /allergySizeInfos/**, 
        - id: product-management
          uri: http://productManagement:8080
          predicates:
            - Path=/products/**, 
        - id: membership-management
          uri: http://membershipManagement:8080
          predicates:
            - Path=/members/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
