---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-fashion-member-management
  labels:
    app: pet-fashion-member-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-fashion-member-management
  template:
    metadata:
      labels:
        app: pet-fashion-member-management
    spec:
      containers:
        - name: pet-fashion-member-management
          image: username/pet-fashion-member-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-management
  labels:
    app: product-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-management
  template:
    metadata:
      labels:
        app: product-management
    spec:
      containers:
        - name: product-management
          image: username/product-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: membership-management
  labels:
    app: membership-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: membership-management
  template:
    metadata:
      labels:
        app: membership-management
    spec:
      containers:
        - name: membership-management
          image: username/membership-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: pet-fashion-member-management
  labels:
    app: pet-fashion-member-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: pet-fashion-member-management


---


apiVersion: v1
kind: Service
metadata:
  name: product-management
  labels:
    app: product-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: product-management


---


apiVersion: v1
kind: Service
metadata:
  name: membership-management
  labels:
    app: membership-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: membership-management

