apiVersion: v1
kind: Service
metadata:
  name: membership-management
  labels:
    app: membership-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: membership-management